### ISSUE TITLE
Blocking operation on load/enable

### ISSUE THREAD

**Issue by SlimeDog** [danirod12/NTD-LuckyBlock#1]
Spigot or Paper 1.18.1
ntdLuckyBlock 2.5.6

On server start-up
```
[16:11:38] [Server thread/WARN]: [LagMonitor] Plugin ntdLuckyBlock is performing a blocking I/O operation (Socket: https://api.spigotmc.org/legacy/update.php?resource=94872) on the main thread. This could affect the server performance, because the thread pauses until it gets the response. Such operations should be performed asynchronous from the main thread. Besides gameplay performance it could also improve startup time. Keep in mind to keep the code thread-safe. Report it to the plugin author
[16:11:38] [Server thread/WARN]: [LagMonitor] The following exception is not an error. It's a hint for the plugin developers to find the source. LagMonitor doesn't prevent this action. It just warns you about it.
java.lang.IllegalAccessException: null
        at com.github.games647.lagmonitor.threading.BlockingActionManager.logCurrentStack(BlockingActionManager.java:65) ~[?:?]
        at com.github.games647.lagmonitor.threading.BlockingActionManager.checkBlockingAction(BlockingActionManager.java:51) ~[?:?]
        at com.github.games647.lagmonitor.listener.BlockingConnectionSelector.select(BlockingConnectionSelector.java:30) ~[?:?]
        at sun.net.www.protocol.http.HttpURLConnection.plainConnect0(HttpURLConnection.java:1232) ~[?:?]
        at sun.net.www.protocol.http.HttpURLConnection$6.run(HttpURLConnection.java:1118) ~[?:?]
        at sun.net.www.protocol.http.HttpURLConnection$6.run(HttpURLConnection.java:1116) ~[?:?]
        at java.security.AccessController.doPrivileged(AccessController.java:712) ~[?:?]
        at java.security.AccessController.doPrivilegedWithCombiner(AccessController.java:962) ~[?:?]
        at sun.net.www.protocol.http.HttpURLConnection.plainConnect(HttpURLConnection.java:1115) ~[?:?]
        at sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.connect(AbstractDelegateHttpsURLConnection.java:175) ~[?:?]
        at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1665) ~[?:?]
        at sun.net.www.protocol.http.HttpURLConnection$9.run(HttpURLConnection.java:1581) ~[?:?]
        at sun.net.www.protocol.http.HttpURLConnection$9.run(HttpURLConnection.java:1579) ~[?:?]
        at java.security.AccessController.doPrivileged(AccessController.java:712) ~[?:?]
        at java.security.AccessController.doPrivilegedWithCombiner(AccessController.java:962) ~[?:?]
        at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1578) ~[?:?]
        at sun.net.www.protocol.https.HttpsURLConnectionImpl.getInputStream(HttpsURLConnectionImpl.java:224) ~[?:?]
        at me.DenBeKKer.ntdLuckyBlock.util.SpigotUpdater.checkForUpdates(SpigotUpdater.java:66) ~[?:?]
        at me.DenBeKKer.ntdLuckyBlock.util.SpigotUpdater.checkForUpdatesFixed(SpigotUpdater.java:59) ~[?:?]
        at me.DenBeKKer.ntdLuckyBlock.util.SpigotUpdater.check$announce(SpigotUpdater.java:95) ~[?:?]
        at me.DenBeKKer.ntdLuckyBlock.LBMain.do(LBMain.java:622) ~[?:?]
        at me.DenBeKKer.ntdLuckyBlock.LBMain.for(LBMain.java:620) ~[?:?]
        at me.DenBeKKer.ntdLuckyBlock.LBMain.int(LBMain.java:260) ~[?:?]
        at org.bukkit.craftbukkit.v1_18_R1.scheduler.CraftTask.run(CraftTask.java:82) ~[spigot-1.18.1-R0.1-SNAPSHOT.jar:3392-Spigot-54b4afa-aeaeb35]
        at org.bukkit.craftbukkit.v1_18_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:415) ~[spigot-1.18.1-R0.1-SNAPSHOT.jar:3392-Spigot-54b4afa-aeaeb35]
        at net.minecraft.server.MinecraftServer.b(MinecraftServer.java:1255) ~[spigot-1.18.1-R0.1-SNAPSHOT.jar:3392-Spigot-54b4afa-aeaeb35]
        at net.minecraft.server.dedicated.DedicatedServer.b(DedicatedServer.java:428) ~[spigot-1.18.1-R0.1-SNAPSHOT.jar:3392-Spigot-54b4afa-aeaeb35]
        at net.minecraft.server.MinecraftServer.a(MinecraftServer.java:1206) ~[spigot-1.18.1-R0.1-SNAPSHOT.jar:3392-Spigot-54b4afa-aeaeb35]
        at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:1034) ~[spigot-1.18.1-R0.1-SNAPSHOT.jar:3392-Spigot-54b4afa-aeaeb35]
        at net.minecraft.server.MinecraftServer.lambda$0(MinecraftServer.java:304) ~[spigot-1.18.1-R0.1-SNAPSHOT.jar:3392-Spigot-54b4afa-aeaeb35]
        at java.lang.Thread.run(Thread.java:833) [?:?]
```

**Comment by danirod12** [comment]
Hello. I will change task to async in 2.5.7 version. Please use discord support server for further reports, because i give support faster on it.

**Comment by SlimeDog** [comment]
Confirmed fixed in ntdLuckyBlock 2.5.7. Thanks.

I wasn't in a hurry. Generally speaking, I don't Discord. Github issues should send you notifications.

**Comment by danirod12** [comment]
Well, you are playing discord already for 10 hours, you are at the top of Spigot MC discord server. Anyway, it is ok to send reports here. Yes, GitHub send me notifications, but i check github only after any of my commits (Sometimes with 4-5 days delay).

**Comment by SlimeDog** [comment]
I am required to monitor the SpigotMC Discord channel, due to my volunteer work as a moderator. It's all well and good for each plugin developer to monitor their particular Discord channel. I cannot, and will not, monitor 170 Discord channels for all the plugins I test and follow. The signal-to-noise ratio is asymptotically zero. Github issues provide focus on ... well ... issues.
