### ISSUE TITLE
NPEs onEnable

### ISSUE THREAD

**Issue by SlimeDog** [danirod12/NTD-LuckyBlock#2]
```
>version
[22:16:29] [Server thread/INFO]: This server is running CraftBukkit version 3409-Spigot-862678e-30b4043 (MC: 1.18.1) (Implementing API version 1.18.1-R0.1-SNAPSHOT)
[22:16:29] [Server thread/INFO]: You are running the latest version
>mc-log mc-check-plugins 75%_*_155 
[22:16:30] [Server thread/INFO]: ========================== mc-check-plugins 75%_*_155 ==========================
>version ntdLuckyBlock
[22:16:33] [Server thread/INFO]: ntdLuckyBlock version 2.5.10
[22:16:33] [Server thread/INFO]: Cool revamped LuckyBlock & API. Say goodbye to the sponge and resourcepacks!
[22:16:33] [Server thread/INFO]: Author: [DenBeKKer]
```
On server start-up, six of these
```
[21:29:55] [Server thread/WARN]: java.lang.NullPointerException: Cannot invoke "me.DenBeKKer.ntdLuckyBlock.d.a.do(org.bukkit.inventory.ItemStack)" because "<local2>" is null
[21:29:55] [Server thread/WARN]:        at me.DenBeKKer.ntdLuckyBlock.customitem.Identifier.apply(Identifier.java:46)
[21:29:55] [Server thread/WARN]:        at me.DenBeKKer.ntdLuckyBlock.customitem.BekkerItemStack.<init>(BekkerItemStack.java:21)
[21:29:55] [Server thread/WARN]:        at me.DenBeKKer.ntdLuckyBlock.customitem.BekkerItemStackBuilder.build(BekkerItemStackBuilder.java:130)
[21:29:55] [Server thread/WARN]:        at me.DenBeKKer.ntdLuckyBlock.customitem.CustomItemFactory.register(CustomItemFactory.java:65)
[21:29:55] [Server thread/WARN]:        at me.DenBeKKer.ntdLuckyBlock.customitem.CustomItemFactory.loadSystem(CustomItemFactory.java:280)
[21:29:55] [Server thread/WARN]:        at me.DenBeKKer.ntdLuckyBlock.LBMain.if(LBMain.java:452)
[21:29:55] [Server thread/WARN]:        at me.DenBeKKer.ntdLuckyBlock.LBMain.onEnable(LBMain.java:264)
[21:29:55] [Server thread/WARN]:        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264)
[21:29:55] [Server thread/WARN]:        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:342)
[21:29:55] [Server thread/WARN]:        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:480)
[21:29:55] [Server thread/WARN]:        at org.bukkit.craftbukkit.v1_18_R1.CraftServer.enablePlugin(CraftServer.java:526)
[21:29:55] [Server thread/WARN]:        at org.bukkit.craftbukkit.v1_18_R1.CraftServer.enablePlugins(CraftServer.java:440)
[21:29:55] [Server thread/WARN]:        at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:612)
[21:29:55] [Server thread/WARN]:        at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:414)
[21:29:55] [Server thread/WARN]:        at net.minecraft.server.dedicated.DedicatedServer.e(DedicatedServer.java:262)
[21:29:55] [Server thread/WARN]:        at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:994)
[21:29:55] [Server thread/WARN]:        at net.minecraft.server.MinecraftServer.lambda$0(MinecraftServer.java:304)
[21:29:55] [Server thread/WARN]:        at java.base/java.lang.Thread.run(Thread.java:833)
```

**Comment by SlimeDog** [comment]
Confirmed fixed in ntdLuckyBlock 2.5.11. Thanks.
